default_stages: ["pre-commit"]
default_install_hook_types: ["pre-commit", "commit-msg"]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  - repo: https://github.com/George-Ogden/linter/
    rev: v1.2.0
    hooks:
      - id: lint
        args: [--fix]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff-format
      - id: ruff-check
        args:
          - --fix
        exclude: ^test_samples/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies: [prettier]

  - repo: https://github.com/George-Ogden/pre-commit-hooks
    rev: v2.0.2
    hooks:
      - id: check-merge-conflict
      - id: dbg-check
      - id: todo-check
      - id: mypy
        args: [-r, requirements-dev.txt, --show-traceback]
        exclude: ^test_samples/
      - id: spell-check-commit-msgs
