[tool.ruff]
line-length = 100
exclude = ["test_samples/"]

[tool.ruff.lint]
extend-select = ["I", "UP", "F", "E", "W", "ERA001", "RUF", "PT"]
extend-ignore = ["F811", "E501", "PT011", "PT012"]

[tool.ruff.lint.isort]
force-sort-within-sections = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.flake8-pytest-style]
parametrize-names-type = "csv"

[tool.mypy]
warn_unreachable = true
disallow_subclassing_any = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
warn_unused_ignores = true
strict_equality = true
exclude = "test_samples"
plugins = ["plugin.py"]

[[tool.mypy.overrides]]
module = "pytest_snapshot.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
python_files = "*_test.py"
addopts = '--capture=sys'
norecursedirs = ["test_samples"]
